/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphicsRouteImport } from './routes/graphics'
import { Route as PrompterRouteImport } from './routes/prompter'
import { Route as RundownRouteImport } from './routes/rundown'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SoundsRouteImport } from './routes/sounds'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsRoute = GraphicsRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrompterRoute = PrompterRouteImport.update({
  id: '/prompter',
  path: '/prompter',
  getParentRoute: () => rootRouteImport,
} as any)
const RundownRoute = RundownRouteImport.update({
  id: '/rundown',
  path: '/rundown',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundsRoute = SoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRoute
  '/prompter': typeof PrompterRoute
  '/rundown': typeof RundownRoute
  '/settings': typeof SettingsRoute
  '/sounds': typeof SoundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRoute
  '/prompter': typeof PrompterRoute
  '/rundown': typeof RundownRoute
  '/settings': typeof SettingsRoute
  '/sounds': typeof SoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRoute
  '/prompter': typeof PrompterRoute
  '/rundown': typeof RundownRoute
  '/settings': typeof SettingsRoute
  '/sounds': typeof SoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/graphics' | '/prompter' | '/rundown' | '/settings' | '/sounds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graphics' | '/prompter' | '/rundown' | '/settings' | '/sounds'
  id:
    | '__root__'
    | '/'
    | '/graphics'
    | '/prompter'
    | '/rundown'
    | '/settings'
    | '/sounds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphicsRoute: typeof GraphicsRoute
  PrompterRoute: typeof PrompterRoute
  RundownRoute: typeof RundownRoute
  SettingsRoute: typeof SettingsRoute
  SoundsRoute: typeof SoundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics': {
      id: '/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof GraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompter': {
      id: '/prompter'
      path: '/prompter'
      fullPath: '/prompter'
      preLoaderRoute: typeof PrompterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rundown': {
      id: '/rundown'
      path: '/rundown'
      fullPath: '/rundown'
      preLoaderRoute: typeof RundownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sounds': {
      id: '/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphicsRoute: GraphicsRoute,
  PrompterRoute: PrompterRoute,
  RundownRoute: RundownRoute,
  SettingsRoute: SettingsRoute,
  SoundsRoute: SoundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
